// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMMaterials.DAL;

#nullable disable

namespace TMMaterials.DAL.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    [Migration("20260218093245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionProperties", b =>
                {
                    b.Property<int>("propertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("propertyId");

                    b.HasIndex("PropertyName")
                        .IsUnique();

                    b.ToTable("tblCollectionProperties");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionPropertiesValues", b =>
                {
                    b.Property<int>("valueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("collectionStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("propertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("valueId");

                    b.ToTable("tblCollectionPropertiesValues");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionStandards", b =>
                {
                    b.Property<int>("collectionStandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("collectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("standardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("collectionStandardId");

                    b.ToTable("tblCollectionStandards");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollections", b =>
                {
                    b.Property<int>("collectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("collectionId");

                    b.ToTable("tblCollections");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblMain", b =>
                {
                    b.Property<int>("mainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceUnits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthUnits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("mainId");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("tblMain");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblMaterialsLibrary", b =>
                {
                    b.Property<int>("libraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("collectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("libraryId");

                    b.ToTable("tblMaterialsLibrary");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblStandards", b =>
                {
                    b.Property<int>("standardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("standardId");

                    b.ToTable("tblStandards");
                });
#pragma warning restore 612, 618
        }
    }
}
