// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMMaterials.DAL;

#nullable disable

namespace TMMaterials.DAL.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionProperties", b =>
                {
                    b.Property<int>("propertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .HasColumnType("TEXT");

                    b.HasKey("propertyId");

                    b.HasIndex("PropertyName")
                        .IsUnique();

                    b.ToTable("tblCollectionProperties");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionPropertiesValues", b =>
                {
                    b.Property<int>("valueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int?>("collectionStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("propertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("valueId");

                    b.ToTable("tblCollectionPropertiesValues");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollectionStandards", b =>
                {
                    b.Property<int>("collectionStandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialGrade")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("collectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mainId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("materialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("standardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("collectionStandardId");

                    b.ToTable("tblCollectionStandards");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblCollections", b =>
                {
                    b.Property<int>("collectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .HasColumnType("TEXT");

                    b.HasKey("collectionId");

                    b.ToTable("tblCollections");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblMain", b =>
                {
                    b.Property<int>("mainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceUnits")
                        .HasColumnType("TEXT");

                    b.Property<string>("LengthUnits")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionName")
                        .HasColumnType("TEXT");

                    b.HasKey("mainId");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("tblMain");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblMaterialTypes", b =>
                {
                    b.Property<int>("materialTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("materialTypeId");

                    b.ToTable("tblMaterialTypes");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblMaterialsLibrary", b =>
                {
                    b.Property<int>("libraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("collectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("libraryId");

                    b.ToTable("tblMaterialsLibrary");
                });

            modelBuilder.Entity("TMMaterials.DAL.Model.tblStandards", b =>
                {
                    b.Property<int>("standardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardName")
                        .HasColumnType("TEXT");

                    b.HasKey("standardId");

                    b.ToTable("tblStandards");
                });
#pragma warning restore 612, 618
        }
    }
}
